### ISSUE TITLE
Issue with ResponsiveGrid inside ScrollViewer

### ISSUE THREAD

**Issue by andreapier** [sourcechord/ResponsiveGrid#1]
Hi,
I have an issue with ResponsiveGrid in a WPF project.
I used it inside a ScrollViewer set to scroll horizontally but not vertically.
The problem is that the grid does not scroll.
Is this the indended behaviour?
Do you know of any workaround?

I'm posting a working example to save you some time (maybe 2 mins :)). You can use it to reproduce the issue.

Thanks for your work

[WpfApplication1.zip](https://github.com/sourcechord/ResponsiveGrid/files/456951/WpfApplication1.zip)

**Comment by sourcechord** [comment]
Hi, andreapier!!

Thanks for your report.
I can reproduce this problem.
Example files that you posted is very helpful for check issues quickly.

And, I began fix this bugs.
I'll fix this issue until next update.
Please wait for a while :)

**Comment by andreapier** [comment]
Very good, looking forward to hearing from you!!
If you need any further info please let me know.

**Comment by sourcechord** [comment]
I fixed it!!
And, released ResponsiveGrid version 0.3.1.
https://www.nuget.org/packages/ResponsiveGrid/0.3.1

Please, try it.

**Comment by andreapier** [comment]
Hi @sourcechord!
The fix in working perfectly!!
I think you can close the issue.

Thank you for taking the time to look at it.

**Comment by sourcechord** [comment]
I'm glad to hear that.
Thank you for your feedback!!

**Comment by mindaugasveb** [comment]
Hi, I found that when you have ResponsiveGrid which has another ResponsiveGrid inside as a child and wrap everything with Scrollviewer, it does only count height of parent ResponsiveGrid, but it does not calculate inner ResponsiveGrid so when you change window height, scrollviewer starts to work only when parent ResponsiveGrid height is reached. To reproduce the problem, I've added project sample.
[WpfApplication1.zip](https://github.com/sourcechord/ResponsiveGrid/files/681010/WpfApplication1.zip)
