### ISSUE TITLE
InvalidOperationException with no Children

### ISSUE THREAD

**Issue by andreapier** [sourcechord/ResponsiveGrid#2]
Hello @sourcechord!
I'm here again because I have another issue. I think it is a bug, which makes the library crash with an [InvalidOperationException](https://msdn.microsoft.com/it-it/library/system.invalidoperationexception%28v=vs.110%29.aspx).
The exception is raised because in `MeasureOverride` method, `group` is empty. So, when you try to get  `totalWidth` and `totalHeight`, above exception occurs.
Specific message is `Sequence contains no elements`.
I'm not quite sure how to correctly fix this. I see more than one possibility here.
If you can give some advise I could try to do a pull request.
Otherwise, you can fix it yourself. I think you are way more skilled than me! :)
What I tried is to `return base.MeasureOverride(availableSize)` if `group` is empty. I'm not sure it is the best fix though.
Let me know if you need any further info.
Thanks again!

**Comment by sourcechord** [comment]
Oops!!

I made a mistake at recent commit.
And, I fixed it and released ResponsiveGrid 0.3.2

InvalidOperationException is thrown when invoking Max/Sum method with empty `group` sequence.
So, I fixed the way of calculate panel's desired size.

`totalSize` is now calculated during `foreach` loop.
(there is no need to invoke LINQ method's like a Max/Sum/GroupBy, etc.

Thank you!
