### ISSUE TITLE
Vertical ScrollViewer issue with nested ResponsiveGrid

### ISSUE THREAD

**Issue by ghost** [sourcechord/ResponsiveGrid#3]
Hi, I found that when you have ResponsiveGrid which has another ResponsiveGrid inside as a child and wrap everything with Scrollviewer, it does only count height of parent ResponsiveGrid, but it does not calculate inner ResponsiveGrid so when you change window height, scrollviewer starts to work only when parent ResponsiveGrid height is reached. To reproduce the problem, I've added project sample.
[WpfApplication1.zip](https://github.com/sourcechord/ResponsiveGrid/files/681010/WpfApplication1.zip)

Here is screen illustrating issue.
1. Window is big enough, so scroll is not needed.
2. Window is smaller so vertical scroll bar should appear.
3. Vertical scrollbar appears.

![untitled-2](https://cloud.githubusercontent.com/assets/4151216/21592533/e81666f2-d116-11e6-86b6-70091fdf3b8b.jpg)

**Comment by sourcechord** [comment]
Hi, @mindaugasveb!
Thanks for your feedback.
I can reproduce this problem.

I'm trying to fix this issue.
Please wait for a while.

**Comment by sourcechord** [comment]
Hi!
I've fixed this issue.
And, release ResponsiveGrid v0.3.3

By the way, ResponsiveGrid is move to GridExtra repository.
https://github.com/sourcechord/GridExtra
Same fix is adopted to GridExtra, too.

If you are interested, please try it.

**Comment by ghost** [comment]
Thanks, it is now working as expected 👍

**Comment by sourcechord** [comment]
I'm glad to help.
Thank you:smile:
